### ISSUE TITLE
Forbid followers to accept non-leader transactions

### ISSUE THREAD

**Issue by mayconamaroCW** [cloudwalk/stratus#1341]
the followers nodes don't check if the source is the current leader

**Comment by carneiro-cw** [comment]
The followers currently (ever since shelving raft) only import transactions, and any `eth_sendRawTransaction` that they receive are forwarded to wherever they are imported from (usually the leader). Since the leader currently does not change and there is no push mechanism for transactions I'm closing this as a non-issue.
