### ISSUE TITLE
Possible logic error on TemporaryStorage for InMemoryTemporaryStorage

### ISSUE THREAD

**Issue by carneiro-cw** [cloudwalk/stratus#278]
If the idea is for `InMemoryTemporaryStorage` to run in parallel some things don't make a lot of sense. For instance the reset function would reset the state (which is also shared) after commiting the changes. This means that if two threads (A, B) are processing transactions in parallel and thread A finishes, it will call commit and reset the state for B. Maybe It would make more sense for the state to not be shared, or even for a single instance of `TemporaryStorage` to be created per thread.

**Comment by dinhani-cw** [comment]
This is why conflict detection was removed from temporary storage here: https://github.com/cloudwalk/stratus/commit/a80f61c8c7035fbf55040aac41d1ab82f89e2973

To make it work, temporary storage needs to have generations that are increased after each commit (or save_account_changes?) instead of being reset. 
Older generations are removed from memory based on some configuration.

**Comment by dinhani-cw** [comment]
TemporaryStorage was refactored to conflict detection work.
